### ISSUE TITLE
Broken links in VDPs for qualitative variables  ReadMe.md file

### ISSUE THREAD

**Issue by DrMaggie** [i-adopt/patterns#2]
It appears that the links to both "Boolean Variable" (https://github.com/i-adopt/patterns/blob/main/qualitative/boolean) and "Qualitative Biology Variable" (https://github.com/i-adopt/patterns/blob/main/qualitative/quantitative_biology) are broken in the "VDPs for qualitative variables" ReadMe file (https://github.com/i-adopt/patterns/blob/main/qualitative/ReadMe.md)- clicking on them results in 404 Not Found errors.

**Comment by mabablue** [comment]
this is now resolved
